### ISSUE TITLE
white contrast border

### ISSUE THREAD

**Issue by zinhuofc** [Khalylexe/Firefox-Rounded-Theme#1]
Hi friend, when I move my mouse to the center of the screen the border turns white, how do I remove this and just have it black?

**Comment by Khalylexe** [comment]
go to userChrome.css and look for this section of the code:
`    #appcontent:not(:-webkit-fullscreen) browser:hover {
        border: 3px solid #23CDB3 !important;
        box-shadow: 0 0 10px 5px rgba(0,0,0,0.5) !important;
    }`
then modify the `border: 3ps solid **#23CDB3**` to what u want
if u don't want the border at all just remove the !important
